# Generated by Django 3.1.4 on 2021-06-18 14:56

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('dob', models.DateField(default='yyyy-mm-dd')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=None)),
                ('mobile1', models.CharField(default='', max_length=10)),
                ('mobile2', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('email', models.CharField(default=None, max_length=250)),
                ('address_1', models.CharField(default='none', max_length=128)),
                ('city', models.CharField(default=None, max_length=64)),
                ('state', models.CharField(default=None, max_length=250)),
                ('zip_code', models.CharField(default=None, max_length=10)),
                ('address_2', models.CharField(blank=True, default=None, max_length=128)),
                ('city2', models.CharField(default=None, max_length=64)),
                ('state2', models.CharField(default=None, max_length=250)),
                ('zip_code2', models.CharField(default=None, max_length=10)),
                ('college', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('degree', models.CharField(default=None, max_length=500)),
                ('year_of_passing', models.CharField(default=None, max_length=4)),
                ('university', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('special_training', models.TextField(blank=True, default=None, null=True)),
                ('council_reg_no', models.CharField(default='a-00000-b-1', max_length=12)),
                ('council_reg_date', models.DateField(default='yyyy-mm-dd')),
                ('council_name', models.CharField(default='', max_length=500)),
                ('experience_years', models.CharField(default=None, max_length=4)),
                ('private_practice', models.TextField(default=None, null=True)),
                ('teacher', models.TextField(default=None)),
                ('reference', models.TextField(blank=True, default=None, null=True)),
                ('research_work', models.TextField(blank=True, default=None, null=True)),
                ('profile_photo', models.FileField(default=None, upload_to=member.models.upload_location)),
                ('registration_certificate', models.FileField(default=None, upload_to=member.models.upload_location)),
                ('degree_certificate', models.FileField(default=None, upload_to=member.models.upload_location)),
                ('postgraduate_certificate', models.FileField(default=None, upload_to=member.models.upload_location)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
