# Generated by Django 3.1.4 on 2021-06-15 15:56

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('dob', models.DateField()),
                ('residence_address', models.TextField()),
                ('pincode', models.CharField(default='', max_length=9)),
                ('male', models.BooleanField(blank=True, default=False, null=True)),
                ('female', models.BooleanField(blank=True, default=True, null=True)),
                ('email', models.EmailField(default=None, max_length=250)),
                ('mobile1', models.CharField(default='', max_length=10)),
                ('mobile2', models.CharField(default='', max_length=10, null=True)),
                ('mobile3', models.CharField(default='', max_length=10, null=True)),
                ('college', models.TextField(blank=True, default=None, null=True)),
                ('degree', models.CharField(default=None, max_length=500)),
                ('year_of_passing', models.CharField(default=None, max_length=4)),
                ('university', models.TextField(blank=True, default=None, null=True)),
                ('degree_certificate', models.FileField(default=None, upload_to=member.models.upload_location)),
                ('postgraduate_certificate', models.FileField(default=None, upload_to=member.models.upload_location)),
                ('special_training', models.TextField(blank=True, default=None, null=True)),
                ('council_reg_no', models.CharField(default='a-00000-b-1', max_length=9)),
                ('council_reg_date', models.DateField(default=None)),
                ('council_name', models.CharField(default='', max_length=500)),
                ('experience_years', models.CharField(default=None, max_length=4)),
                ('private_practice', models.TextField(default=None, null=True)),
                ('teacher', models.TextField(default=None)),
                ('experience_certificate', models.FileField(default=None, upload_to=member.models.upload_location)),
                ('reference', models.TextField(blank=True, default=None, null=True)),
                ('research_work', models.TextField(blank=True, default=None, null=True)),
                ('registration_certificate', models.FileField(default=None, upload_to=member.models.upload_location)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
