# Generated by Django 3.1.4 on 2021-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20210615_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='university',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
