# Generated by Django 3.1.4 on 2021-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20210615_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='residence_address',
        ),
        migrations.AddField(
            model_name='member',
            name='address_1',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='address_2',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='zip_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
