# Generated by Django 3.1.4 on 2021-06-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20210615_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='pincode',
        ),
    ]
