# Generated by Django 3.1.4 on 2021-06-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_member_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mobile3',
        ),
    ]
