# Generated by Django 3.1.4 on 2021-06-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_remove_member_mobile3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='council_reg_date',
            field=models.DateField(default='yyyy-mm-dd'),
        ),
    ]
