# Generated by Django 3.1.4 on 2021-06-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20210616_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='experience_certificate',
            new_name='profile_photo',
        ),
    ]
