# Generated by Django 3.1.4 on 2021-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20210616_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='city2',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='member',
            name='state2',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='zip_code2',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
