# Generated by Django 3.1.4 on 2021-08-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210429_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.TextField(default=None),
        ),
    ]
