# Generated by Django 3.1.4 on 2021-09-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_speakers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
