# Generated by Django 3.1.4 on 2021-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210609_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='designation',
            field=models.CharField(default='', max_length=150),
        ),
    ]
