# Generated by Django 3.1.4 on 2021-06-09 13:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210609_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/default.png', null=True, upload_to=accounts.models.upload_location),
        ),
    ]
