# Generated by Django 3.1.4 on 2021-06-10 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'All gallery',
                'verbose_name_plural': 'All gallery',
            },
        ),
        migrations.CreateModel(
            name='ResourcesBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default=None, max_length=250)),
                ('pdf_link', models.TextField(default=None)),
                ('author_name', models.TextField(default=None)),
                ('publisher_detail', models.TextField(blank=True, default=None)),
                ('details', models.TextField(blank=True, default=None)),
                ('clickable_text', models.TextField(default='Download pdf')),
            ],
            options={
                'verbose_name': 'Resource Books',
                'verbose_name_plural': 'Resource Books',
            },
        ),
        migrations.CreateModel(
            name='ResourcesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(default=None, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default=None, max_length=150)),
                ('event_info', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'Upcoming Events pop up',
                'verbose_name_plural': 'Upcoming Events pop up',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2021, 6, 10, 23, 58, 43, 811572))),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='VideoSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_sidebar', models.TextField(blank=True, default=None)),
                ('videos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.TextField(blank=True, default=None)),
                ('videos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.video')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_of_resource', models.TextField(default=None)),
                ('clickable_text', models.TextField(default='Click here')),
                ('links', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.resourcescategory')),
            ],
            options={
                'verbose_name': 'Resource Links',
                'verbose_name_plural': 'Resource Links',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, upload_to=home.models.upload_location)),
                ('gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
            },
        ),
    ]
