# Generated by Django 3.1.4 on 2021-03-15 03:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default=None, max_length=250)),
                ('pdf_link', models.TextField(default=None)),
                ('clickable_text', models.TextField(default='Click here')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default=None, max_length=150)),
                ('event_info', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 10, 33, 822877))),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='VideoSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_sidebar', models.TextField(blank=True, default=None)),
                ('videos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.TextField(blank=True, default=None)),
                ('videos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.video')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_of_resource', models.TextField(default=None)),
                ('clickable_text', models.TextField(default='Click here')),
                ('links', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.resourcescategory')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, upload_to=home.models.upload_location)),
                ('gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.gallery')),
            ],
        ),
    ]
