# Generated by Django 3.1.4 on 2021-03-15 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210315_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 13, 0, 652501)),
        ),
    ]
