# Generated by Django 3.1.4 on 2021-03-15 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210315_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesbooks',
            name='author_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='resourcesbooks',
            name='details',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='resourcesbooks',
            name='publisher_detail',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 17, 29, 479056)),
        ),
    ]
