# Generated by Django 3.1.4 on 2021-03-23 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210315_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 23, 28, 36, 574402)),
        ),
    ]
