# Generated by Django 3.1.4 on 2021-04-29 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210323_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galleries', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='resourcesbooks',
            options={'verbose_name': 'Resources Books', 'verbose_name_plural': 'Resources Books'},
        ),
        migrations.AlterModelOptions(
            name='resourcescategory',
            options={'verbose_name_plural': 'Resource Categories'},
        ),
        migrations.AlterModelOptions(
            name='resourceslinks',
            options={'verbose_name': 'Resources Links', 'verbose_name_plural': 'Resources Links'},
        ),
        migrations.AlterModelOptions(
            name='upcomingevents',
            options={'verbose_name': 'Upcoming Events pop up', 'verbose_name_plural': 'Upcoming Events pop up'},
        ),
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 10, 39, 7, 161492)),
        ),
    ]
