# Generated by Django 3.1.4 on 2021-05-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210429_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'All gallery', 'verbose_name_plural': 'All gallery'},
        ),
        migrations.AlterModelOptions(
            name='resourcesbooks',
            options={'verbose_name': 'Resource Books', 'verbose_name_plural': 'Resource Books'},
        ),
        migrations.AlterModelOptions(
            name='resourceslinks',
            options={'verbose_name': 'Resource Links', 'verbose_name_plural': 'Resource Links'},
        ),
        migrations.AlterField(
            model_name='resourcesbooks',
            name='clickable_text',
            field=models.TextField(default='Download pdf'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 13, 26, 55, 630063)),
        ),
    ]
