# Generated by Django 3.1.4 on 2021-09-08 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210908_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 11, 14, 5, 835338)),
        ),
        migrations.DeleteModel(
            name='VideoSidebar',
        ),
    ]
