# Generated by Django 3.1.4 on 2021-09-08 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210908_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodisplay',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 19, 52, 2, 850090)),
        ),
    ]
