# Generated by Django 3.1.4 on 2021-09-23 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210923_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 13, 30, 11, 642694)),
        ),
    ]
